spring.application.name=Spring-Boot-Backend
spring.datasource.url=jdbc:mysql://localhost:3306/student_db
spring.datasource.username=root
spring.datasource.password=viratkohli

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
service.jwt.secret=77+9U3ByaW5nU2VjdXJpdHlQcmFjdGljZVNlY3JldEtleTIwMjY3N+9Q